document.addEventListener("DOMContentLoaded", function () {
    const storyContainer = document.getElementById("story-container");

    // Data for each chapter (image source or text)
    const chapters = [
        { image: "images/cover2.png", text: "Julia Kohn  |  CRP 3850 - Mapping and Countermapping  |  Professor Wenfei Xu  |  Fall 2023"},
        { image: "images/white_.png", text: "This project visualizes access to parks, walkability, and health metrics in New York City. Being one of the densely populated, compact, and fast-paced cities in the United States, it is crucial to ensure residents not just access to parks, but access to quality, usable, and safe spaces within the built urban environment. Park inequity is an issue that goes beyond physical access to parks, and when paired with socioeconomic disparities, can play a harmful role in shaping neighborhoods throughout the city. The following maps and explanations strive to analyze if and how access to parks and walkability influence health in New York City as a whole, and individual boroughs and areas, and what other factors specific to those areas may be influencing the health of residents." },
        { image: "images/F1_nycparks_map1.png", text: "This map was created using NYC OpenData’s Parks Properties 2023 dataset. The data was used to visualize the geographic locations and shapes of green spaces managed partially or completely by the NYC Parks organization in all five boroughs. This data has been produced in whole or part using secondary data. Data was collected by NYC Parks, and is updated and adjusted as the land designated under the organization’s jurisdiction expands or changes. The main limitation to this data is the constant changing, expansion, and shrinking of parks that is not always updated in real time. However, most of the green spaces shown are consistent."},
        { image: "images/F1_walkingdistance_map2.png", text: "This map was created using NYC OpenData’s Wall-to-a-Park Service 2023 dataset. The NYC Parks organization collected this data based on an analysis of what parts of the city are within 0.5 mile walking distance to an established park that is either over 8 acres large or on a waterfront, or within 0.25 mile walking distance to small green spaces such as sitting areas or playgrounds. This analysis does not include areas within walking distance to green spaces such as cemeteries, community gardens used solely for growing food, or sites with no ability to be used for recreational purposes or leisure. Parks that are privately owned and also have no relation to the NYC Parks organization are also excluded, such as small parks only available to residents of luxury buildings." },
        { image: "images/F1_walkabilityandparks_map4.png", text: "This map was created using filtered data from the United States Environmental Protection Agency’s National Walkability Index dataset. The map is filtered to show the June 2021 walkability scores for New York, categorized by the 2019 Census block groups. A walkable space, with a high level of walkability, is defined as a space that is easy to walk around. There are several factors that the Environmental Protection Agency (EPA) considers to influence walkability the most, and the walkability score for a given area is calculated based on sub-scores for each influencing factor. These factors are characteristics of the built environment that impact the likelihood of walking to be chosen as a mode of transportation for any individual. These factors include street intersection density (number of intersections), proximity to transit stops, and diversity of land usage. According to the EPA, higher street intersection density leads to higher walkability, since a higher number of intersections allows for easier and faster connectivity between spaces. Higher proximity to transit stops is also associated with higher walkability. Regarding land use, areas with a high percentage of mixed use buildings (residential and commercial) are associated with a higher walkability, as well as areas with a large number of commercial-only buildings that are occupied by various employment types and companies from varying industries. In contrast, areas with a high percentage of residential-only buildings, as well as areas concentrated with commercial buildings occupied by only one company or companies of only one industry, are associated with a lower walkability score. However, areas with residential-only buildings that hold many units or apartments often correlate with a higher walkability score, in contrast to buildings that are single-family or hold a small number of separate units. To get the official score for a block group level, each block gets a score for the above 4 categories (street intersection density, proximity to transit stops, land usage regarding employment mix, and land use regarding residential or commercial mix) up to 20, and then put into an equation that finds a weighted average (some factors are weighted higher than others - intersection density and proximity to transit). The scores are given out of 20. The equation is as follows:"},
        { image: "images/Walk_Eq.png", text: "Potential score limitations include that many main streets with popular landmarks in urban areas do not have transit stops directly in the block, but nearby. This could lower the walkability score for main streets, but increase it for surrounding streets." },
        { image: "images/Diabetes_final.png", text: "This map was made using data from the Centers for Disease Control and Prevention’s PLACES Project, visualizing the percentage of the adult population diagnosed with diabetes by census tract in New York in 2020. The data is a one-year modeled estimate, meaning that the estimates for each location are based on data collected throughout one year. Many of the areas that have no data available are spaces taken up by green space or industrial sites, however, some were inconclusive. The strength of this dataset is that it only measures those living with diabetes, and does not count deaths from diabetes. This is a strength, becsuse it is difficult to identify diabetes as the cause of death in many situations, and so if counted those could lead to inaccuracies. A limitation of this data is that approximately 1 in 4 cases of diabetes are undiagnosed, so the data shown is likely to be an underestimation. The data also does not factor in children who have diabetes, and it relies on self-reports of people who say they have been diagnosed, which can lead to inaccuracies as well. The equation for this dataset is as follows:" },
        { image: "images/Diab_Eq.png"},
        { image: "images/Obesity_final.png",text: "This map was made using data from the Centers for Disease Control and Prevention’s PLACES Project, visualizing the percentage of the adult population that is considered obese by census tract in New York in 2020. The data is also a  one-year modeled estimate, and uses the body mass index (BMI) as a metric. The data collected categorizes adults with a BMI of 30 or higher as obese. BMI is used because it often directly correlates with measures of body fat levels. However, this also poses a limitation to the data, since BMI does not account for an individual’s gender, age, ethnicity, or build, all of which have the potential to influence body weight. The data also does not factor in obesity levels in children, which is a large issue in New York. The data also uses self-reported height and weight measures to calculate BMI, which can lead to inaccuracies. However, self-reported height and weight measures are also the most efficient and easiest way to collect this data. The equations used for BMI and obesity in this dataset are as follows:" },
        { image: "images/BMI_Eq.png" },
        { image: "images/Ob_Eq.png"},
        { image: "images/SItitle.png", text: "Following analyses, Staten Island as a whole raised interesting questions about parks and walkability in relation to diseases. Staten Island has a higher walkability index than average, but very high rates of obesity. The area has fairly average diabetes rates as well as amount of space within walking distance to a park."},
        { image: "images/si_1.png", text: "Most of the borough of Staten Island has a walkability index score of over 13, placing it above the national average walkability score of 10.50. By most standards, Staten Island would be considered a very walkable area. However, when looking at how much of the borough is within walking distance to a park (dataset records areas within 0.5 mile walk to an established park, or .25 mile walk to an unofficial green sitting area or small playground), Staten Island is one of the areas in the city with the least easy access to parks. Interestingly enough, the parts of Staten Island that have the highest walkability scores, namely the neighborhoods of Westerleigh, Concord, and Tottenville, are also considered to not be within walking distance to a park. " },
        { image: "images/diob_FINALcomp.png", text: "An interesting point to consider about Staten Island is that regardless of if an area is considered to be walkable and/or within walking distance to a park, the obesity rates in the borough are much higher than the rest of the city. Most studies that have been conducted to analyze the correlation between walkability and obesity have found that less walkable areas have higher obesity rates, while more walkable areas have lower obesity rates. In the case of Staten Island, this conclusion is not valid. In addition, studies that have been conducted to show the correlation between walkability and diabetes have found that less walkable areas have higher diabetes rates, while more walkable areas have lower diabetes rates. Regarding Staten Island, this conclusion would be true. Staten Island does not have a higher diabetes rate than average in New York, nor are there any areas that have abnormal spikes in diabetes levels. If anything, the areas in Staten Island with higher walkability scores, and that are closest to major green spaces, seem to have lower diabetes rates. The inconsistency between the rates of the two diseases in Staten Island is intriguing. If access to green space IS a factor impacting the obesity rate in Staten Island, it may be due to a lack of usage of major parks. One park in particular that may be suffering from a lack of usage is Freshkills Park."},
        { image: "images/Freshkills.png", text: "One of the larger green spaces in Staten Island is Freshkills Park, established on top of the former Fresh Kills Landfill. The landfill was once the largest in the world, but it closed in 2001 and upon greenifying the space, it was established as a park. The park covers 2,200 acres, almost three times the size of Central Park in Upper Manhattan. The park currently has many public, recreational facilities available for users, such as basketball courts, soccer fields, short hiking trails, and playgrounds. As of 2023, more recreational spaces are in the process of being built. These spaces include kayak and boat launches, horseback riding trails, running and bike paths, park houses, pavilions, educational facilities, and wildlife preservation systems. Most of these new programs are planned to be complete by 2036, if not earlier. While so many amenities and plans would make it seem like it would be a popular park to enjoy among Staten Island residents, this is not the case for much of the population."},
        { image: "images/white_.png", text: "Despite efforts to renew and improve the space, many residents still hold negative views towards the park because of its history as a landfill. Many residents hold these views because of environmental concerns, and worries about being exposed to toxins from the landfill that could lead to adverse health impacts such as asthma or cancer. These worries have turned many Staten Island residents from wanting to use the park. Thus, despite it being such a large green space with much recreational potential, in a very walkable area as well, the park is likely not being used nearly as much as one may think. Perhaps the low usage of the green space could help explain higher obesity rates in the area. It is also not surprising that Staten Island residents are wary of the park, considering that when it was still a landfill, those that lived close by experienced respiratory and other health issues and their quality of life was reduced due to constant unpleasant odors." },
        { image: "images/white_.png", text: "“I think mainly people don’t use it [Freshkills Park] because a lot of it isn’t open to the public yet, and older Islanders remember the garbage dump and how it used to smell horrible. They think that going to the park is dangerous.”  —Eric, Staten Island resident" },
        { image: "images/white_.png", text: "Residents’ perceptions of the park raise questions about whether or not measures have been taken by the city to ensure safety in the park and the neighboring communities. This also questions why so much effort has been put into beautifying the park and establishing recreational facilities and opportunities for activities, but there is a lack of effort being put into resources for residents to understand the park and potential safety measures being taken. This is especially interesting because of the size the park takes up at 2,200 acres, which is more than twice the size of Central Park, which is constantly being used by locals and tourists alike. The future of Freshkills Park may rely on the city’s efforts to reduce park inequity,  bring people in and engage them in using the park." },
        { image: "images/white_.png" },
        { image: "images/MWtitle.png", text: "Midtown West in this case refers to the area of Midtown Manhattan that includes part of Hell’s Kitchen and the western part of Manhattan south of Central Park. This area is intriguing in this context because of its surprisingly low walkability index scores, but also low diabetes and obesity rates. The area is mostly within walking distance to a park, but given its small size and density, this is expected. The only part of this area that has high disease rates is the census tract group that includes Times Square, which has high rates of both diabetes and obesity."},
        { image: "images/MidtownWest_Walk.png", text: "This neighborhood is home to Broadway theaters and popular tourist attractions that bring thousands to the area every day. Thus, it is also home to some of the busiest subway stations in the city, including the Times Square 42nd Street station on the 123 subway line. These characteristics of the area make the low walkability rates very surprising."},
        { image: "images/MidtownWest_Dis.png", text: "One explanation for the low walkability rates could be traffic congestion. New York is ranked as the worst city for traffic congestion in the United States, but Midtown Manhattan traffic is especially difficult because of the neighborhood’s proximity to the Lincoln Tunnel, its many large schools in the area, and a high number of Ubers and taxis driving through the area due to its attractions. However, it is not only traffic on the roads that deters people from walking around the area. “Foot traffic” refers to traffic congestion within spaces where the main mode of transportation is walking. According to New Yorkers, Midtown Manhattan has considerably bad foot traffic. Due to the high amounts of attractions and stores in the neighborhood, it is quite a crowded place. New Yorkers report trying to walk in the bike lanes and the sides of the streets instead of the sidewalks when foot traffic gets bad, which then worsens car traffic as well. This has caused a jaywalking problem, and some New Yorkers have reported that they try to cross the street before the light changes in order to get ahead of other pedestrians. In fact, in 2023, over 70% of New Yorkers have reported that they regularly jaywalk. This causes safety issues for pedestrians and drivers alike. The New York City Department of Transportation has deemed Midtown West as having the worst foot traffic in the entire city."},
        { image: "images/white_.png", text: "Low disease rates in Midtown despite low walkability rates could be a result of socioeconomic statistics. In 2018, Midtown Manhattan had an 11% poverty rate, compared to 14% for all of Manhattan and 20% for all of New York City. In addition, only 5% of Midtown was unemployed, compared to 7% for all of Manhattan and 9% for the whole city. Midtown is also 68% white, 15% Asian, 10% hispanic, only 3% black, and 4% other races."},
        { image: "images/white_.png", text: "Other reasons for low disease rates in Midtown could be easy access to healthcare. 11% of Midtown residents reported having no health insurance, which is lower than the city-wide average at 12%. Only 8% of adults in Midtown reported not receiving needed medical care, which is also lower than the city-wide average at 10%. Midtown also had a higher rate of adults who got the influenza vaccination, at 51% compared to the average for the city at 41%. Around 87% of residents reported eating fruits and vegetables daily, and only 11% reported consuming sugary drinks daily. Midtown is also home to popular but expensive gyms, which are often financially accessible to those living in Midtown."},
        { image: "images/white_.png" },
        { image: "images/NQtitle.png", text: "The northeastern region of Queens is home to the neighborhoods of Flushing, Murray Hill, College Point, and Whitestone. Northeast Queens is an example of an area with predictable statistics in this context, with high walkability index scores, fair access to parks and green space, very low obesity rates, and relatively low diabetes rates as well."},
        { image: "images/flushing1.png"},
        { image: "images/flushing2.png", text: "The correlation between the data could lead one to assume that the accessibility of parks and high walkability in northeast Queens has had great impacts on keeping disease levels low. This may be somewhat true, but one particular part of this area stands out against this assumption. The census tract groups right above Flushing Meadows Corona Park, one of the largest parks in the city at roughly 897 acres, also has one of the highest diabetes rates in the borough. However, it is also among the lowest obesity rates in the city. Flushing is 52% Asian, and individuals of East Asian ethnicities are often at a higher risk for diabetes than people of other races and ethnicities. People of East Asian origin are simultaneously at the lowest risk of obesity. This could explain the disparity in the statistics in Flushing in particular." },
        { image: "images/flushingmeadows.png",text: "A reason behind the extremely low obesity rates could also be related to the fast renovation and development of Flushing Meadows-Corona Park. The park was originally a marsh and dump-site, known by the public as “Corona Ash Dump”. The space went through a period of fast development when urban planner Robert Moses decided the park would host the 1939-1940 World’s Fair. The 1964-1965 World’s Fair was later hosted there too, as well as the temporary United Nations complex before it moved to Manhattan. The park holds the Unisphere, a globe-like structure built for the second World’s Fair in Queens, which still brings tourists into the park to this day. Other attractions in the park include the Billie Jean King National Tennis Center, where the annual U.S. Open Tennis Championship is held, the Queens Zoo, and the New York Hall of Science. The park is now complete with man-made lakes, lawns, barbecue spaces, sports fields, hiking trails, and recreational facilities. The excitement of hosting the fair brought attention to the park from people all over the city, but it is widely used by residents of nearby neighborhoods. The timing of the development of the park also coincided with the end of the Great Depression and the New Deal, which furthered this excitement over the park." },
        { image: "images/white_.png" },
        { image: "images/LBtitle.png", text: "The South Bronx area is home to the neighborhoods of Melrose, Mott Haven, Port Morris, Longwood, and Woodstock. This space is interesting to analyze in this context because the trends among the data are almost exactly the opposite of what one might assume, yet possibly skewed by demographic and socioeconomic factors as well." },
        { image: "images/southbronx.png"},
        { image: "images/southbronx2.png", text: "Most of the census tract groups within the South Bronx have high walkability scores, and almost the entire area is considered to be within walking distance to a park. However, both the diabetes and obesity rates are much higher than the average for the city. In fact, almost the entire South Bronx area is within the highest category for both diabetes and obesity, according to the datasets used. Every census tract group in the South Bronx has an obesity rate of at least 28.6%." },
        { image: "images/white_.png", text: "Given the high walkability index scores and short walking distance to parks throughout the area, it can be easily assumed that the high disease rates are not due to access to green spaces. This is also likely due to the fact that many other parts of the city with similar walkability scores, such as Flushing, Queens, have much lower disease rates." },
        { image: "images/white_.png", text: "Another thing to note is that the South Bronx has a significant difference in income levels as compared to areas with lower disease rates. In 2021, the median household income for the South Bronx was $32,381. While this is a 30.9% increase from the average of $24,742 in 2011, it is still barely above the poverty threshold in New York of roughly $27,000. In comparison, the median household income in Midtown Manhattan as of 2023 is $131,635—almost a $100,000 difference.  In addition, while Midtown is 68% white, 15% Asian, 10% hispanic, only 3% black, and 4% other, the South Bronx is 57.1% hispanic, 39.8% black, 1.4% white, and 0.5% Asian. This raises questions about the racial and ethnic impact on both health in these areas, as well as park equity and attention or lack thereof to park development.  This also brings up the question of if the size and development of parks is related to demographics, despite physical access to parks or proximity to parks from homes." },
        { image: "images/stmarys.png", text: "A potential explanation for the imbalance between park access and disease rates in the South Bronx could also be a disparity over what the parks, green spaces, and other public spaces in the area are actually used for. With approximately 90,000 residents combined, the neighborhoods of Port Morris and Mott Haven share a singular park within a densely populated and compactly built area. This is St. Mary’s Park, located between the two communities. This park is the largest green space in the South Bronx, yet is still considerably small at around 35 acres. In comparison, Central Park is approximately 843 acres in size. To put that into perspective, Central Park is around 24 times larger than the largest park in the South Bronx." },
        { image: "images/white_.png", text: "The area around St. Mary’s Park is also considered to be extremely walkable. However, while people in the area have physical access to the parks, they do not have the same recreational access to St. Mary’s and other green spaces as compared to residents of parks like Central Park. St. Mary’s Park has reportedly been taken over by industrial manufacturing sites, and much of the park that is still purely green space is underdeveloped or abandoned. Members of the South Bronx Unite organization have been working with architects and partner institutions towards green space equity and the restoration of park access in the South Bronx with immense effort. Despite having easy access to the park and a high walkability rate, higher than most of Manhattan even, it is clear that the substance of the park is extremely important in understanding why park access may not have a positive impact on disease reduction in the South Bronx as it potentially might in other areas." },
        { image: "images/white_.png"},
        { image: "images/crown.png", text: "Crown Heights is an area in eastern Brooklyn that is home to the neighborhoods of Brownsville, East Flatbush, and southern Bedford Stuyvesant. The part of Brooklyn is situated in between Prospect Park and Highland Park. Crown Heights is interesting because while the area is mostly in close proximity to small parks or sitting areas, Prospect and Highland part are almost entirely inaccessible to these neighborhoods. The area also has low walkability scores, and high disease rates."},
        { image: "images/crown1.png" },
        { image: "images/crown2.png", text: "Similarly to the South Bronx, the parks in Crown Heights are all very small, with one of the main parks, Brower Park, being only 7 acres in size. Another popular park is St. John’s Park, which takes up 9 acres. The New York Times claims that poorer areas in New York have smaller parks, and wealthier areas have larger parks, but data comparing Crown Heights to the South Bronx refutes this. The racial and ethnic demographics of Crown Heights are very different from the South Bronx, but both share the commonality of not being predominantly white areas. As of 2021, Crown Heights was 43.4% black, 28.1% white, 15% hispanic, and 5.1% Asian. The median household income for Crown Heights is $99,583, which is higher than that of the South Bronx at $32,381. However, one point made by the New York Times that is proven correct is that in neighborhoods that are predominantly black, the average park size is 7.9 acres."},
        { image: "images/white_.png", text: "Crown Heights also had the 2nd highest diabetes rate in the city in 2015 at 16%, and the 6th highest obesity rate at 33%. When comparing this to the 2020 data in the map, not much has changed at all. The area also ranks 14th in the city for physical activity, with 79% of residents reporting that they have had any physical activity within the last 30 days. However, the area has a higher percentage of smokers than average for the city at 17%, as well as a higher percentage of people who consume at least 1 sugary drink per day at 37%. This may lead one to believe that the high diabetes and obesity rates could be explained by the smoking and eating habits of residents."},
        { image: "images/white_.png", text: "While that may be a contributor, it is difficult not to notice the stark lack of easy access to adequately sized parks. With a population of over 100,000 people, parks that are not even 10 acres large are simply not big enough. In comparison, St. Mary’s Park in the South Bronx is roughly 843 acres in size and serves 90,000 people, yet still is not perceived as large enough for the neighborhoods that use it."},
        { image: "images/white_.png", text: "Crown Heights  also neighbors Park Slope, a neighborhood with much easier access to Prospect Park, and a higher average income at $150,320 in 2021. Park Slope's racial and ethnic demographics in 2021 also came out to be 63.4% white, 7.54% Asian, 7.34% black, and 6.03% hispanic. As seen on the maps above, Park Slope, which is northwest of Crown Heights, has lower disease rates as well. While the direct reason for Crown Heights’ high disease rates is hard to decipher, it is clear that there is a major difference in the substance and size in the area’s parks compared to those in whiter, wealthier neighborhoods nearby. Park inequity in Brooklyn could be what is holding Crown Heights back from days of better health."},
        { image: "images/white_.png" },
        { image: "images/white_.png" },
        { image: "images/white_.png" },
        { image: "images/white_.png" },
        { image: "images/white_.png" },
        { image: "images/white_.png", text: "Sources" },
        { image: "images/bib1.png"},
        { image: "images/bib2.png"}
    ];

 const formattedChapters = chapters.map(chapter => {
        if (chapter.mainText) {
            return `${chapter.textBefore || ''}${chapter.mainText}\n\nBefore Image: ${chapter.image}\n\nAfter Image: ${chapter.image}\n\n`;
        } else {
            return `${chapter.text}\n\n`;
        }
    

});

console.log(formattedChapters.join(""));



    // Loop through chapters and create HTML elements dynamically
    chapters.forEach((chapter, index) => {
        const chapterElement = document.createElement("div");
        chapterElement.classList.add("chapter");

        const imageElement = document.createElement("img");
        imageElement.src = chapter.image;
        imageElement.alt = `Chapter ${index + 1} Image`;
        imageElement.classList.add("center-image", "fade-in");

        const textElement = document.createElement("p");
        textElement.textContent = chapter.text;

        chapterElement.appendChild(imageElement);
        chapterElement.appendChild(textElement);

        storyContainer.appendChild(chapterElement);
    });

// Add the fade-in effect when scrolling
    const images = document.querySelectorAll('.fade-in');

    const options = {
        threshold: 0.5,
    };

    const handleIntersection = (entries, observer) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                entry.target.classList.add('visible');
                observer.unobserve(entry.target);
            }
        });
    };

    const observer = new IntersectionObserver(handleIntersection, options);

    images.forEach(image => {
        observer.observe(image);
    });
});